name: Phoenix Nutrition
favicon: null
layout_spectrum: 0.36312
typography_spectrum: 0.8282
title: Phoenix Nutrition
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0a1b'
    - '#bba478'
    - '#e35d00'
    - '#f7270d'
    - '#eccf78'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
