name: Phoenix Nutrition
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8282
title: Phoenix Nutrition
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f22a3a'
    - '#fe3495'
    - '#ff8149'
    - '#ff6661'
    - '#ff4e77'
  brandStrength: 0.875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
