name: Phoenix Nutrition
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8282
title: Phoenix Nutrition
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#173c8d'
    - '#011762'
    - '#aea3cd'
    - '#ec727f'
    - '#b12d5f'
  brandStrength: 0.22100726794451475
  lightness: 0.47753735864534974
  saturation: 0.854086703620851
  rhythmicContrast: 0.7406311493832618
purpose: []
